services:
  iris:
    container_name: iris-ice
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 1972:1972
      - 52773:52773
    volumes:
      - ./:/home/irisowner/dev
    #  - ./tmp:/tmp